/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iuEscritorio;

import controladores.ControladorCargaSaldoPropietario;
import javax.swing.JOptionPane;
import logica.Propietario;
import controladores.IVistaCargaSaldoPropietario;

/**
 *
 * @author Usuario
 */
public class RecargaSaldoDialogo extends javax.swing.JDialog  implements IVistaCargaSaldoPropietario{

    /**
     * Creates new form RecargaSaldo
     */
    public ControladorCargaSaldoPropietario controladorCargaSaldoPropietario;
    public RecargaSaldoDialogo(java.awt.Frame parent, boolean modal, Propietario propietario) {
        super(parent, modal);
        initComponents();
        controladorCargaSaldoPropietario = new ControladorCargaSaldoPropietario(this, propietario);
//        labelNombreUsuario.setText(controladorCargaSaldoPropietario.mostrarDetallePropietario());
//        valueSaldo.setText(String.valueOf(controladorCargaSaldoPropietario.mostrarSaldoPropietario()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNombreUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputMonto = new javax.swing.JTextField();
        btnAceptarRecarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Saldo : ");

        labelSaldo.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Usuario : ");

        labelNombreUsuario.setText("jLabel3");

        jLabel3.setText("Monto a Recargar");

        inputMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMontoActionPerformed(evt);
            }
        });

        btnAceptarRecarga.setText("Aceptar");
        btnAceptarRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRecargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(inputMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSaldo)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNombreUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnAceptarRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelSaldo)
                    .addComponent(jLabel2)
                    .addComponent(labelNombreUsuario))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnAceptarRecarga)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRecargaActionPerformed
    
        controladorCargaSaldoPropietario.agregarRecargaSaldo(Double.parseDouble(inputMonto.getText()));     
      
    }//GEN-LAST:event_btnAceptarRecargaActionPerformed

    private void inputMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMontoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRecarga;
    private javax.swing.JTextField inputMonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JLabel labelSaldo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarDetallePropietario(String nombre, double saldo) {
        labelSaldo.setText(String.valueOf(saldo) );
        labelNombreUsuario.setText(nombre);
    }

    @Override
    public void RecargaCreada() {
        inputMonto.setText("");
        // se está solicitando que este componente reciba el enfoque, es decir, que esté listo para recibir eventos de entrada.
        //Esto podría ser útil si deseas que el usuario pueda ingresar otro nombre inmediatamente después de realizar una recarga.
        inputMonto.requestFocus();
    }

    @Override
    public void error(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
}
